baseURL: "http://me.renj.io"
languageCode: "zh-CN"
title: "Resume Renj.io"
theme: "PagerMod"
params:
  profileMode:
    enabled: true
    title: "ä½ å¥½ğŸ˜, æˆ‘æ˜¯Renj Liao"
    subtitle: "æˆ‘æ˜¯ä¸€åwebå¼€å‘å·¥ç¨‹å¸ˆ"
    imageUrl: "/origin.jpg"
    imageTitle: "avatar"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Hello, äº†è§£ä¸€ä¸‹
        url: /hello/
  socialIcons:
    - name: github
      url: https://github.com/landers1037
    - name: email
      url: mailto:liaorenj@gmail.com
    - name: stackoverflow
      url: https://stackoverflow.com/users/11940188/landers1037
    - name: steam
      url: https://steamcommunity.com/id/pipi831143
    - name: facebook
      url: https://fb.me/landers1037
    - name: youtube
      url: https://www.youtube.com/channel/UCAvTanPSk_wl_2V-EpUfJiA
    - name: telegram
      url: https://t.me/Greatpipi
